name: cashify
description: "Para registrar tus movimientos financieros en pocos pasos."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  cloud_firestore: ^5.6.12
  collection: ^1.19.1
  equatable: ^2.0.8
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter_dotenv: ^6.0.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  intl: ^0.19.0
  provider: ^6.1.5+1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - env/dev.env
    - env/prod.env
  uses-material-design: true
